# Login to Azure subscription
name: 'Azure ARM Deploy'
description: 'Deploys an azure arm template to azure at a resource group level'
inputs: 
  resource_group: 
    description: 'Resource group on which the resource has to be deployed'
    required: false
    default: false
  mode:
    description: 'The deployment mode.  Allowed values: Complete, Incremental.  Default: Incremental.'
    required: false
    default: 'Incremental'
  name:
    description: 'The deployment name.'
    required: false
    default: undefined
  rollback_on_error:
    description: 'The name of a deployment to roll back to on error, or use as a flag to roll back to the last successful deployment.'
    required: false
    default: false
  template_file: 
    description: 'The path to the template file'
    required: true
    default: undefined
  parameter_file:
    description: 'The path to the parameters file'
    required: false
    default: undefined
  parameters:
    description: 'the parameters directly as as <KEY=VALUE> pairs'
    required: false
    default: undefined
branding:
  icon: 'login.svg'
  color: 'blue'
runs:
  using: 'node12'
  main: 'lib/main.js'
