# Deploy your ARM template at resource group level
name: 'Azure ARM Deploy'
description: 'Deploys an azure arm template to azure at a resource group level'
inputs: 
  scope:
    description: 'Scope of deployment either of these < resource_group, subscription, management_group, tenant >'
    required: true
  location:
    description: 'location where deployment has to happen: NOt required if deployment on resource group '
    required: true
  resource_group: 
    description: 'Resource group on which the resource has to be deployed : required when scope is resource group'
    required: false
  management_group_id:
    description: "The management group id to create deployment at : only required when scope is management group"
    required: false
  mode:
    description: 'The deployment mode.Allowed values: Complete, Incremental.  Default: Incremental.'
    required: false
    default: ''
  name:
    description: 'The deployment name.'
    required: false
    default: ''
  rollback_on_error:
    description: 'The name of a deployment to roll back to on error, or use as a flag to roll back to the last successful deployment.'
    required: false
    default: ''
  template_file: 
    description: 'The path to the template file'
    required: true
    default: ''
  parameter_file:
    description: 'The path to the parameters file'
    required: false
    default: ''
  parameters:
    description: 'the parameters directly as as <KEY=VALUE> pairs'
    required: false
    default: ''
outputs:
  deployment_status:
    description: 'Status of the deployment'
  deployment_result:
    description: 'deployment error details in case status is Failed'
branding:
  color: 'blue'
runs:
  using: 'node12'
  main: 'lib/index.js'
