# Test Actions train a model on Azure Machine Learning  
name: aml-deploy-infrastructure 
on:
  push:
    branches:
      - master

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checking out repo code'
        uses: actions/checkout@v2

      - uses: azure/login@v1.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: test action
        id: sampletest
        uses: mlopstemplates/arm_deploy@master
        with:
            resource_group: "testgroup"
            template_file: "/.cloud/.azure/deploy.json"
            parameter_file: "/.cloud/.azure/deploy.params.json"
      
      - name: Display deployment output details
        run: |
          echo deployment_status: ${{ steps.sampletest.outputs.deployment_status}}
          echo deployment_error: ${{ steps.sampletest.outputs.deployment_error}}